### PR TITLE
feature.623: admin functionality

### PR DESCRIPTION
**Pull request by gabriel-tincu**
Add admin functionality using the AIOKafkaClient underneath, plus unit tests for most methods.
Used kafka-python logic wherever possible to keep the footprint as light as possible

Related to https://github.com/aio-libs/aiokafka/issues/623

### CODE REVIEW

**Comment by abuckenheimer** [comment]
would love to see this get merged eventually

**Comment by david-alm** [comment]
To provide additional signal, I'd also love to see this merged.

**Comment by tvoinarovskyi** [comment]
Sorry for not going over this all this time, will get it merged soon.
@gabriel-tincu Great thanks for working on this, it's very simple and matches with what I wanted for the AdminClient.

**Review by tvoinarovskyi — APPROVED** [review]

**Comment by ods** [comment]
Merged as part of #811

**Pull request closed without merging**
