### PR TITLE
Fix typing bugs found by beartype

### PR DESCRIPTION
**Pull request by ods**
Try [pytest-beartype](https://github.com/beartype/pytest-beartype), as [suggested](https://github.com/aio-libs/aiokafka/issues/980#issuecomment-1987811336) by @antonagestam . Only two bugs found so far, doesn't seem enough to add it to CI.

### CODE REVIEW

**Comment by antonagestam** [comment]
Cool stuff, I hope it at least brings some confidence to the type hints 👍

**Comment by ods** [comment]
> I hope it at least brings some confidence to the type hints 👍

Unfortunately it doesn't catch even simple and obvious bugs. So, I'd like to find another runtime checker.

**Comment by antonagestam** [comment]
@ods FWIW, there's also typeguard: https://github.com/agronholm/typeguard

**Comment by ods** [comment]
> FWIW, there's also typeguard: https://github.com/agronholm/typeguard

Right, but the use is not as simple as "install and add command line option", as it is with beartype

**Pull request merged**
