### PR TITLE
Add tests against Kafka 1.0.1

### PR DESCRIPTION
**Pull request by castarco**
Just to improve the confidence that we as developers can have on AIOKafka, it would be nice to see how it works against Kafka 1.0.1.

### CODE REVIEW

**Comment by webknjaz** [comment]
Tests fail

**Comment by castarco** [comment]
Yeah, we should push a new Docker image to the DockerHub registry for Kafka 1.0.1. But strangely TravisCI is not complaining about the missing Docker image.

**Comment by webknjaz** [comment]
Probably pytest suppresses that or somehow picks odd image. Can you reproduce this locally?

**Comment by castarco** [comment]
I'll try to check it this evening (Berlin time)

**Comment by tvoinarovskyi** [comment]
@castarco Thanks for the PR, I will need to build and update an image for Kafka 1.0.1. It requires custom docker image to build.

**Comment by tvoinarovskyi** [comment]
I've fully updated travis.yml, so will fix this along with #413. Will be 1.0.2 Kafka, hope you don't mind

**Pull request closed without merging**
