### PR TITLE
Support async with in the consumer

### PR DESCRIPTION
**Pull request by nimish**
## What do these changes do?

Adds `async with` -- PEP 492 -- support in the consumer 

## Are there changes in behavior for the user?

Not really, just support for 

`async with AIOKafkaConsumer(....) as foo: pass`

## Related issue number

None

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by nimish** [comment]
@tvoinarovskyi is there anything I can do to get the codecov working? I'm not sure why it's picking up so many changes.

**Comment by tvoinarovskyi** [comment]
Sorry for such a late response. We had several talks about allowing the context manager for Consumer/Producer. My concern was that mostly this is used as "acquire connection" in a lot of drivers and I wanted to avoid confusion when it closes the whole thing after context, but later looking at aiohttp with ClientSession it feels like not as bad of a solution.
As for codecov, I have no idea how to fix it yet, only recently did I discover it's completely broken. It's related to the move on travis.com from travis.org, it can't access coverage file. Ignore it for now)

**Comment by nimish** [comment]
Cool. Let me know how you'd like to proceed here.

**Comment by tvoinarovskyi** [comment]
I will pull the change set manually.

**Comment by nimish** [comment]
For contributers.txt: `Nimish Telang <nimish@telang.net>`

**Comment by tvoinarovskyi** [comment]
Closing in favour of #613

**Pull request closed without merging**
