### PR TITLE
Improve send performance (#943)

### LINKED ISSUE #943: performance degradation of producer when having many topics
**Describe the bug**
When a kafka cluster has many topics like 5k or more, the performance of the producer degrades drastically. 
I compared the performance with that of kafka-python. Here is the summary.
```
Running Tests for Kafka-Python
Starting benchmark for Kafka-Python producer.
Kafka-Python producer Results:
Number of Runs: 5, Number of messages: 100000, Message Size: 100 bytes.
Average Time for 100000 messages: 7.028003358840943 seconds.
Messages / sec: 14228.792289093612
MB / sec : 1.3569633759587871
===================
Running Tests for AIOKafka
/root/workspace/news/kafka-client-benchmarks/aiokafka-benchmark.py:40: DeprecationWarning: The loop argument is deprecated since 0.7.1, and scheduled for removal in 0.9.0
  producer = AIOKafkaProducer(loop=loop, **producer_config)
Starting benchmark for AIOKafka Producer.
AIOKafka Producer Results:                   
Number of Runs: 5, Number of messages: 100000, Message Size: 100 bytes.
Average Time for 100000 messages: 54.26867785453796 seconds.
Messages / sec: 1842.6835506853604
MB / sec : 0.17573199755529026
===================
```
aiokafka producer's perf is almost 1/10. 

In my environment, kakfa cluster has more than 5000 topics.
I noticed the number of topics affects `producer.send` function every time. SO, I will send PR to fix this.

**Expected behaviour**
Even when # of topics becomes large, aiokafka producer is faster than kafka-python producer.   

**Environment (please complete the following information):**
 - aiokafka version (`python -c "import aiokafka; print(aiokafka.__version__)"`):
 ```
# pip list | grep kafka
aiokafka                              0.8.1       
kafka-python                      2.0.2
```
 - Kafka Broker version (`kafka-topics.sh --version`): 
 - Other information (Confluent Cloud version, etc.): On-Premises

**Reproducible example**
To measure performance I used the code here https://github.com/abhishekray07/kafka-client-benchmarks/tree/master

### PR DESCRIPTION
**Pull request by ods**
### Changes

Fixes #943 

The results of `benchmark/simple_produce_bench.py`:

- before: 120101.0 m/s
- after: 141686.0 m/s

### CODE REVIEW

**Review by uchiiii — APPROVED** [review]
Thank you! @ods 

This LGTM and I measured the performance on the same environment using this modification.
Here is the result.

```
Running Tests for Kafka-Python
Starting benchmark for Kafka-Python producer.
Kafka-Python producer Results:
Number of Runs: 5, Number of messages: 100000, Message Size: 100 bytes.
Average Time for 100000 messages: 6.893932819366455 seconds.
Messages / sec: 14505.508339025255
MB / sec : 1.3833530749345069
===================
Running Tests for AIOKafka
kafka-client-benchmarks/aiokafka-benchmark.py:40: DeprecationWarning: The loop argument is deprecated since 0.7.1, and scheduled for removal in 0.9.0
  producer = AIOKafkaProducer(loop=loop, **producer_config)
Starting benchmark for AIOKafka Producer.
AIOKafka Producer Results:
Number of Runs: 5, Number of messages: 100000, Message Size: 100 bytes.
Average Time for 100000 messages: 1.3094082355499268 seconds.
Messages / sec: 76370.37654494504
MB / sec : 7.283246664518837
===================
```

Improved more than #942, so I close #942.

**Comment by ods** [comment]
> BTW, is it possible to make this fix available some way soon?

I'm going to include it into 0.9.0rc1, probably on Wednesday. Then we need some feedback before doing final release, especially from people using snappy and zsdt compression.

**Comment by ods** [comment]
Pre-release with fix [is ready](https://pypi.org/project/aiokafka/0.9.0rc1/), please check

**Comment by uchiiii** [comment]
Thank you for your work. I confirmed everything works well!

**Pull request merged**
