### PR TITLE
Update kafka-python to new version

### LINKED ISSUE #369: Python 3.7 support: kafka-python >= 1.4.3 required
`async` is a reserved keyword in Python 3.7. This was not properly handled in kafka-python versions prior to 1.4.3. In order to support Python 3.7 in aiokafka, kafka-python version must be updated to >= 1.4.3

### PR DESCRIPTION
**Pull request by tvoinarovskyi**
Needed to fix #369

### CODE REVIEW

**Comment by tvoinarovskyi** [comment]
Hmm, 3.7 seems to actually have several problems. Ehh, no easy way(

**Comment by tvoinarovskyi** [comment]
Will need to reconfigure how SSL self-signed certificates are generated. They need a full, proper config to correctly match hostnames. For now disabled that.

**Comment by webknjaz** [comment]
You may try https://trustme.readthedocs.io (and other possible helpers: https://github.com/cherrypy/cheroot/issues/95)

**Comment by tvoinarovskyi** [comment]
@webknjaz https://trustme.readthedocs.io looks promising.

**Pull request merged**
