### PR TITLE
WIP: SCRAM-SHA-256 and -512

### PR DESCRIPTION
**Pull request by SukiCZ**
## What do these changes do?`

Adds support for `SCRAM-SHA-256` & `SCRAM-SHA-512`

## Are there changes in behavior for the user?

No changes, just extending current behaviour

## Related issue number

#517

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

## TODO

I wasn't able to setup Kafka correctly in unit-test runner. I was trying to do so in commit 6c3159c4 but I think maybe ZooKeeper needs to be configured as well. Any help here would be appreciated.

Thanks in advance.

### CODE REVIEW

**Comment by tvoinarovskyi** [comment]
@SukiCZ Great thanks, all works, it only needs the docker images to be rebuilt. For now, I did not implement the automatic deployment of docker images for testing, sorry for that. Will update the images and fix CI in master. 
Thanks for working on this!

**Comment by SukiCZ** [comment]
@tvoinarovskyi Thanks for taking your part in tests :heart_decoration: I couldn't invest more time on this :disappointed:

**Comment by tvoinarovskyi** [comment]
@SukiCZ No worries, great job. I had a bit of trouble debugging but got it working. FYI the only missing part was calling this function: 
```python
    def _add_scram_user(self):
        self.out("Adding SCRAM credentials for user {} to zookeeper.".format(self.broker_user))
        args = self.kafka_run_class_args(
            "kafka.admin.ConfigCommand",
            "--zookeeper",
            "%s:%d/%s" % (self.zookeeper.host,
                       self.zookeeper.port,
                       self.zk_chroot),
            "--alter",
            "--entity-type", "users",
            "--entity-name", self.broker_user,
            "--add-config",
            "{}=[password={}]".format(self.sasl_mechanism, self.broker_password),
        )
        env = self.kafka_run_class_env()
        proc = subprocess.Popen(args, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        stdout, stderr = proc.communicate()

        if proc.returncode != 0:
            self.out("Failed to save credentials to zookeeper!")
            self.out(stdout)
            self.out(stderr)
            raise RuntimeError("Failed to save credentials to zookeeper!")
        self.out("User created.")
```
You seem to need to add user not only to "jaas" config, but also into Zookeeper. I still don't understand what is username/password in JAAS config used for...

**Comment by tvoinarovskyi** [comment]
Also read about it here: https://docs.confluent.io/2.0.0/kafka/sasl.html

**Comment by Neustradamus** [comment]
@SukiCZ: Thanks a lot for all about SCRAM.

Can you edit your main description with the good issue number?
It is #571.

Note that @ran-ka has found a bug: https://github.com/aio-libs/aiokafka/pull/789

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by SukiCZ** [comment]
Hi @Neustradamus
I've updated `Related issue number` guess that was a typo. I'm glad this feature have helped you :')

**Pull request merged**
