### PR TITLE
fix AIOKafkaProducer contextmanager

### PR DESCRIPTION
**Pull request by shamrin**
### Changes

`AIOKafkaProducer` currently doesn't work as a context manager:

```python
async with AIOKafkaProducer(loop=asyncio.get_event_loop(), **kafka_params()) as producer:
        await producer.send_and_wait(KAFKA_TOPIC, b'message data')
```

It fails with `AttributeError: 'NoneType' object has no attribute 'send_and_wait'`.

### Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by shamrin** [comment]
The change it's pretty straightforward, only a single line of code. Do you think it could get merged without going through the whole checklist? `AIOKafkaProducer` is the only context manager that is broken at the moment, others works fine. For example, ``AIOKafkaConsumer`.

**Comment by omikader** [comment]
+1 Can this be merged soon?

**Comment by ods** [comment]
It would be nice to add test cases for all context managers

**Comment by shamrin** [comment]
@ods thank you for your reply! Unfortunately, I don't have time to write the tests. I'm no longer using aiokafka actively. Somebody else is welcome to write them. @omikader? :)

In the meantime, here is the work around I've used in the past:

```python
import aiokafka

class AIOKafkaProducer(aiokafka.AIOKafkaProducer):
    """Same as aiokafka class, but can be used as a context manager

    TODO remove the class once the fix is merged: https://github.com/aio-libs/aiokafka/pull/701
    """

    async def __aenter__(self):
        await self.start()
        return self
```

**Comment by omikader** [comment]
Ok take a look at #729, I don't think it needed that many changes to unit tests. The `AIOKafkaConsumer` class already had this check so I added it to the tests for the `AIOKafkaProducer`

**Comment by shamrin** [comment]
Awesome, thank you @omikader!

**Pull request closed without merging**
