### PR TITLE
Fix issue #536 

### PR DESCRIPTION
**Pull request by tvoinarovskyi**
For race condition between metadata update and subscription change

### CODE REVIEW

**Comment by rjemanuele** [comment]
This patch works for a few iterations and then several exceptions are raised.  Test code and logs below:

consumer.py
```
from aiokafka import AIOKafkaConsumer
import asyncio
import random
import logging

loop = asyncio.get_event_loop()

consumer = None


async def consume():
    global consumer

    consumer = AIOKafkaConsumer(
        loop=loop, bootstrap_servers='kafka.bus:9092', metadata_max_age_ms=5000
    )
    # Get cluster layout and topic/partition allocation
    await consumer.start()
    try:
        async for msg in consumer:
            logging.info("consumed: %s" % msg.value)
    finally:
        await consumer.stop()


async def topic_updater():
    while True:
        i = random.randint(1, 3)
        topic = "my_topic{}".format(i)
        if consumer is not None:
            logging.info('subscribing: %s' % topic)
            consumer.subscribe([topic, 'mytopic-static'])
        await asyncio.sleep(10)

loop.set_debug(True)
my_format = "%(asctime)s - %(levelname)s : %(name)s : %(message)s"
logging.basicConfig(level=logging.DEBUG, format=my_format)
loop.run_until_complete(asyncio.gather(consume(), topic_updater()))
```

[log.txt](https://github.com/aio-libs/aiokafka/files/3489497/log.txt)

**Comment by tvoinarovskyi** [comment]
@rjemanuele Great, this seems to be a separate issue. It does update subscription successfully but failed later on. Have no idea how to fix this one yet.

**Comment by rjemanuele** [comment]
Hi @tvoinarovskyi, Any update on this?

**Comment by tvoinarovskyi** [comment]
@rjemanuele Sorry, not really, hard to find time atm. Thanks for pinging, will try to get some time this week!

**Comment by tvoinarovskyi** [comment]
@rjemanuele Reworked the patch, turned out dirty, but should cover your case fully now. Sorry for taking forever 🙇

**Pull request merged**
